tap "1password/tap"
tap "bigwig-club/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Modern replacement for 'ls'
brew "exa"
# Distributed revision control system
brew "git"
# Simple zero-configuration command-line HTTP server
brew "http-server"
# Keep your Mac's application settings in sync
brew "mackup"
# Mac App Store command-line interface
brew "mas"
# Open source relational database management system
brew "mysql"
# Node version management
brew "n"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP/2 C Library
brew "nghttp2"
# 📦🚀 Fast, disk space efficient package manager
brew "pnpm"
# Pretty, minimal and fast ZSH prompt
brew "pure"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Perl-powered file rename script with many helpful built-ins
brew "rename"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Zsh prompt for Astronauts
brew "spaceship"
# Secure Reliable Transport
brew "srt"
# Terminal multiplexer
brew "tmux"
# CLI tool that moves files or folder to the trash
brew "trash"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# JavaScript package manager
brew "yarn"
# UNIX shell (command interpreter)
brew "zsh"
# Command-line helper for the 1Password password manager
cask "1password-cli"
# Application launcher and productivity software
cask "alfred4"
# Enable Windows-like alt-tab
cask "alt-tab"
# Menu bar icon organizer
cask "bartender"
# Translation application for text, pictures, and manual input
cask "bob"
# Web debugging Proxy application
cask "charles"
# Screen capturing tool
cask "cleanshot"
# Disk space visualizer
cask "daisydisk"
# Teamwork app by Alibaba Group
cask "dingtalk"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker"
# Downloads videos from different websites
cask "downie"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Reimagine your terminal
cask "fig"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
# GIT client
cask "fork"
# Finder replacement and FTP, SFTP, WebDAV and Amazon s3 client
cask "forklift"
cask "go2shell"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Utility to hide menu bar items
cask "hiddenbar"
# Free and open-source media player
cask "iina"
# System monitoring app
cask "istat-menus"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Keyboard customizer
cask "karabiner-elements"
# File archiver
cask "keka"
# Interface for reading and syncing eBooks
cask "kindle"
# Open-source Epub reader with backup and restore support
cask "koodo-reader"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Music streaming platform
cask "neteasemusic"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# All system and utility switches in one place
cask "one-switch"
# Client program for the OpenVPN Access Server
cask "openvpn-connect"
# HTTP client that helps testing and describing APIs
cask "paw"
# PDF reader, editor and annotator
cask "pdf-expert"
# PDF compression tool
cask "pdf-squeezer"
cask "pennywise"
# Converts and edits video, audio or image files
cask "permute"
# Collaboration platform for API development
cask "postman"
# Instant messaging tool
cask "qq"
# Move and resize windows using keyboard shortcuts or snap areas
cask "rectangle"
# MySQL/MariaDB database management platform
cask "sequel-pro"
# Team communication and collaboration software
cask "slack"
# Input method supporting full and double spelling
cask "sogouinput"
# Music streaming service
cask "spotify"
# Tencent cloud gaming platform
cask "start"
# Network toolbox
cask "surge"
# Remote access and connectivity software focused on security
cask "teamviewer"
# Messaging app with a focus on speed and security
cask "telegram"
# Configurable document editor that supports Markdown
cask "typora"
# Open-source code editor
cask "visual-studio-code"
# Rust-based terminal
cask "warp"
# Free messaging and calling application
cask "wechat"
# Browse & Control phone on PC, Screen Fusion for iOS & Android
cask "wormhole"
mas "1Password for Safari", id: 1569813296
mas "Bob", id: 1630034110
mas "Dato", id: 1470584107
mas "Drafts", id: 1435957248
mas "iMovie 剪辑", id: 408981434
mas "Keynote 讲演", id: 409183694
mas "Manico", id: 724472954
mas "MenubarX", id: 1575588022
mas "MindNode", id: 1289197285
mas "Numbers 表格", id: 409203825
mas "Pages 文稿", id: 409201541
mas "PasteNow", id: 1552536109
mas "Spark", id: 1176895641
mas "Speedtest", id: 1153157709
mas "Twitter", id: 1482454543
mas "uPic", id: 1549159979
mas "库乐队", id: 682658836
